### ISSUE TITLE
detect wifi devices

### ISSUE THREAD

**Issue by marvin-bitterlich** [PH111P/powerline#11]
Currently the wireless device name is hardcoded. We should instead detect this automatically and f.e. show the best connected device. Or one segment per device.

**Comment by PH111P** [comment]
As one has possibly multiple wireless devices, it is not clear how to determine the correct one. Further, as one does not normally change these devices that often anyway, writing a single device name into a configuration file each time your device does happen to change, does not seem to be that much of a bother to me.
