### ISSUE TITLE
Add config file for icon mapping

### ISSUE THREAD

**Issue by marvin-bitterlich** [PH111P/powerline#13]
Currently we have to specify all icons for each i3 mode.

We should instead have one file specifying the icons mapped to windows. And then override some of these in specific modes.

**Comment by PH111P** [comment]
In fact, you only have to specify the icons for every workspace icon, which is desirable in general. 
Further, you can now specify the new/changed icons only, which should result in a much cleaner config file. Also, if you let me know about these additional icons, I may just include them into the default configuration.
