### ISSUE TITLE
Fix lag problems

### ISSUE THREAD

**Issue by marvin-bitterlich** [PH111P/powerline#15]
Using the bar for longer times makes it have a noticeable delay when switching workspaces.

Some systems have this delay initially.

**Comment by PH111P** [comment]
This seems to be a system specific bug.

**Comment by PH111P** [comment]
Do you use the powerline-daemon?

**Comment by PH111P** [comment]
If you use the powerline-daemon, which client do you use?

**Comment by PH111P** [comment]
As I cannot reproduce this issue, and you didn't provide enough details to further look into this, I have to close this issue fur now.
