### ISSUE TITLE
Thunderbird integration

### ISSUE THREAD

**Issue by marvin-bitterlich** [PH111P/powerline#23]
Storing imap user and password in plain text is not recommended.

Also many users have thunderbird open anyway. So we could grap customizable counters from there instead of requesting everything twice. This would also allow multiple email accounts.

**Comment by PH111P** [comment]
I think that the IMAP segment is targeted especially at users who _don't_ have any other email client open. Further, one can already have multiple instance of the IMAP segment at the same time.
