### ISSUE TITLE
Multi-Monitor Support

### ISSUE THREAD

**Issue by marvin-bitterlich** [PH111P/powerline#25]
Having multiple monitors means Lemonbar renders multiple times on the currently active monitor.

This seems totally random and not intended.

**Comment by PH111P** [comment]
This bug seems to apply for monitor configurations where one is above another.

**Comment by TimJones** [comment]
I am also having this problem, when install on Arch Linux with AUR package https://aur.archlinux.org/packages/powerline-i3-git/

**Comment by PH111P** [comment]
Having monitors in a setup like this
```
+----+
|    |
+----+
|    |
+----+
```
should start working with commit 927fb40, however more testing is required.

**Comment by PH111P** [comment]
Apparently, this is a bug in the lemonbar. To workaround this, try using my bar fork (https://github.com/ph111p/bar) and then pass the flags `--alt_output` and `--bar_command` to `powerline-lemonbar`.
