### ISSUE TITLE
Workspace name issues

### ISSUE THREAD

**Issue by ghost** [PH111P/powerline#26]
Scenario 1:
2 workspaces (with fancy fontawesome icons):
1  web
2  term
Scenario 2:
2 workspaces (without fancy fontawesome icons):
1web
2term

Scenario 1:
I click on 2  term (to go to it), but it sends me to a new workspace called '2'
Same with 1  web, but instead it goes to '1'
Scenario 2:
I click on 2term, but it sends me to '2t'
Same with 1web, but instead it goes to '1w'

I could just change my workspaces names but :/

Also, extra question how to disable window icons?

**Comment by ghost** [comment]
I see that disabling icons will fix it on other issue, but how?

**Comment by PH111P** [comment]
If you disable the icons, you can get arbitrary workspace switching by removing the `:.2` from the click configuration of the workspace and scratch segments:

    "workspace": { "fg": "0xe4e4e4", "bg": "0x0087af", "click": { "left": "i3-msg workspace {0}", "right": "i3-msg move to workspace {0}" } },
    "workspace:urgent": { "bg": "0x0087af", "fg": "0xffaf00", "click": { "left": "i3-msg workspace {0}", "right": "i3-msg move to workspace {0}" } },

You can disable icons by setting the corresponding argument to `{ }`

**Comment by ghost** [comment]
@PH111P I see that, but the problem is that I dont know where are the settings. .config/powerline?
where?! Please help.

**Comment by PH111P** [comment]
Ah, sorry. 
Yeah, the powerline settings are in `.config/powerline`; `.config/powerline/themes/wm/default.json` to be precise. If that file does not exist, copy it from `/path to powerline installation root/powerline/config_files/themes/wm/default.json`,
where `/path to powerline installation root/`is something like `/usr/lib/python3.6/site-packages/` or `/usr/lib/python3.6/site-packages/powerline_status_i3-1.4.1-py3.6.egg/` depending on your powerline installation.

**Comment by PH111P** [comment]
See also #21.
