### ISSUE TITLE
extend clickable by "hover"

### ISSUE THREAD

**Issue by LuckyLukert** [PH111P/powerline#27]
It would be nice to have the events "enter" and "exit" for an segment.
Background: I would like to show conky on enter and close conky on exit so conky would show up while hovering.

**Comment by PH111P** [comment]
As it seems I will need to maintain my own bar fork due to #25, I consider adding hovering events to that fork. That aside, I plan on implementing segments having multiple states.

**Comment by LuckyLukert** [comment]
What just came to my mind:

You could change the content depending on wether the mouse is hovering.
- detailed information on hover
- basic information while mouse is elsewhere

**Comment by PH111P** [comment]
(Some) segments can now shrink/grow after clicking (etc.) on them (via the `#bar;ch_fill` and `#bar;ch_clear` bar commands), thus using a lemonbar fork that supports hover enter and exit events should make auto-grow/shrink possible.
Sadly, I'm not aware of any such lemonbar fork, thus for the time being one has to simulate this behavior by using the bar command `#bar;ch_toggle` instead (which toggles between the short and the long version of supported segments).
As of version `1.7`, the various player segments, the Google Calendar segment and the Wi-Fi segment support this.

**Comment by PH111P** [comment]
Starting with 52a367583bdef54bf6f24dfaf82057db3e58f883 powerline now supports the `hover enter` and `hover leave` click events. Note that the only lemonbar fork implementing these click events that I'm aware of is https://github.com/PH111P/bar (available from AUR as `powerline-clicks-git`), and that implementation is far from perfect.
