### ISSUE TITLE
powerline not compatible with python3.4 anymore

### ISSUE THREAD

**Issue by tjbcg** [PH111P/powerline#28]
Powerline is not compatible with python3.4 anymore because of the file `renderer.py`.

Python 3.4 throws an exception (SyntaxError) on this line (and two other very similar ones)
```python
contents_highlighted = self.hl(self.escape(contents_raw), **segment['highlight'], **segment)
```

Commenting out these lines make powerline work again, but segements are empty.

This can probably be easily fixed by passing `bg=`, `fg=`, `attrs=` instead of using parameter expansion (`**segment['highlight']`)

**Comment by PH111P** [comment]
Fixed. Thanks for your fix!
