### ISSUE TITLE
No more cpu segment ?

### ISSUE THREAD

**Issue by tjbcg** [PH111P/powerline#29]
Is the cpu usage segment gone ? I can't seem to find it in the docs, and the one in my config simply stopped working.

Are there reasons for this ?

Also, I've always wondered, would it be difficult to add a shell command segment ? That would be really nice, as it would allow for very easy custom segments (and for cpu usage too !)

**Comment by PH111P** [comment]
There should be a cpu load segment (`powerline.segments.common.sys.cpu_load_percent`).
(It should also appear in the docs, I'll investigate.) 
There could be multiple reasons why the segment is not shown, however. First, it could be that, for whatever reason, the python `psutil` module is not available on your system anymore. Second, it could be that you have set priorities in your powerline config and the bar truncates itself, removing the cpu load segment in the process.
For a shell command segment, that should be easy to implement and I see the benefits of having one, so it will probably happen.

**Comment by tjbcg** [comment]
I have this segment in my config, and it simply stopped showing up. Also, the [documentation doesn't seem to know it either](https://powerline-i3.readthedocs.io/en/latest/search.html?q=cpu&check_keywords=yes&area=default). Also, `psutil` is installed.

**Comment by PH111P** [comment]
Does the segment show up again if you remove some other segment?

**Comment by PH111P** [comment]
For the docs, when I build them locally, documentation for the cpu load segment is generated. I'll look into it.

**Comment by PH111P** [comment]
The docs are fixed now. [https://powerline-i3.readthedocs.io/en/latest/configuration/segments/common.html#system-properties](https://powerline-i3.readthedocs.io/en/latest/configuration/segments/common.html#system-properties)

**Comment by tjbcg** [comment]
The segment does not show up. It's definitely not a truncation issue as I have plenty of space ([see this screenshot of my lemonbar](https://i.imgur.com/DZbgVk4.png))

**Comment by tjbcg** [comment]
So, actually, I got it working. The issue was that psutil was installed as a python3.4 package while I was running powerline with python3.6. Should I create a separate issue for the shell segment proposition ?

**Comment by PH111P** [comment]
Documentation for the generic shell document is available at https://powerline-i3.readthedocs.io/en/latest/configuration/segments/common.html#module-powerline.segments.common.generic; if you need more features or encounter any problems, feel free to open an issue.
