### ISSUE TITLE
Make clock segment expand on mouse hover

### ISSUE THREAD

**Issue by LuckyLukert** [PH111P/powerline#34]
like the wifi-segment

**Comment by PH111P** [comment]
This is now possible with enhanced segment selectors:
* Add an `include_function`/`exclude_function` to the segment you want to conditionally hide/show/shrink using e.g. the `powerline.selectors.i3wm.channel_full` selector:
``` JSON
            {
                "function":             ...,
                "args": { ... },
                "include_function": {
                    "function":         "powerline.selectors.i3wm.channel_full",
                    "args": {
                        "channel_name": "<chan_name>"
                    }
                },
                ...
            },
```
* In your color scheme, add corresponding click events filling and clearing the respective channel:
``` JSON
                "hover enter":  "#bar;ch_fill@<chan_name>",
                "hover leave":  "#bar;ch_clear@<chan_name>",
```

There are also a corresponding selector (`powerline.selectors.i3wm.channel_has_value`) and bar command (`#bar;pass:<value>@<chan_name>`) to listen to / send specific values.
