### ISSUE TITLE
Weather Segment displays incorrect tempature

### ISSUE THREAD

**Issue by LividJava** [PH111P/powerline#37]
The weather segment is displaying an erroneous leading 5 when using Fahrenheit and a trailing 2 when using Celsius .
![image](https://github.com/PH111P/powerline/assets/7604544/e17ca71e-d7f3-4060-9ed8-b079caa5d3cd)
![image](https://github.com/PH111P/powerline/assets/7604544/ab093ff5-34e2-4511-a0c6-e67e205ef8d8)

**Comment by LividJava** [comment]
Celsius display might actually be correct just no decimal

**Comment by PH111P** [comment]
Hi @LividJava,

Could you please share the config-files that you use?

**Comment by LividJava** [comment]
https://gist.github.com/LividJava/c7df7051b94b7ec343a55b8033898afd

These are the config files im using for WM

**Comment by PH111P** [comment]
Thanks!
I think I found the problem: It seems as if per default, the API returns the temperature in some weird unit. I think that explicitly specifying proper units in the API call should fix this.
@LividJava, can you please test if commit https://github.com/PH111P/powerline/commit/2997d707dbd26de67b3d87477e81d40ea250f584 fixes this issue for you?

**Comment by LividJava** [comment]
Appears to be working now! Closing
