### ISSUE TITLE
Request under kbd segment, Show current layout

### ISSUE THREAD

**Issue by LividJava** [PH111P/powerline#38]
I swap between keyboard layouts pretty often, and i'd like to see an indicator for it on Powerline, i know there exists a segment for lock status, is there a possibility for Layout indicator as well? `setxkbmap -query` might be a good wrapped command for this

**Comment by PH111P** [comment]
Hi @LividJava,

You should be able to use the `generic_shell` segment for your purpose. In particular, wrapping the command `setxkbmap -query | awk '/layout/ {print $2}'` should do the trick.

(You might want to adjust the highlight group below.)

```
{
    "function":             "powerline.segments.common.generic.generic_shell",
    "args": {
        "command":          "setxkbmap -query | awk '/layout/ {print $2}'",
        "highlight_groups": ["keyboard"]
    }
}
```

**Comment by LividJava** [comment]
I was trying to find documentation on this! appreciate it!
