### ISSUE TITLE
Leere Teil-Segmente bei leerem Gamify-Segment

### ISSUE THREAD

**Issue by LuckyLukert** [PH111P/powerline#5]
Bei folgender Konfiguration wird ein leeres Segment (wahrscheinlich für den heart-Bereich, der leer ist) links von dem Blitz/der Batterie angezeigt. Das hat vor einem der letzten Updates funktioniert.
 ```
{
    "function": "powerline.segments.common.bat.battery",
    "args": {
        "gamify": true,
        "steps": 0,
        "online": "",
        "full_heart": "",
        "half_heart": "",
        "empty_heart": "",
        "offline": "",
        "bat": 0
    }
}
```

**Comment by PH111P** [comment]
v1.3 starts supporting this use case. Note that it could be that the  character may be considered of different length by different applications.
